tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "autojump"
brew "fzf"
brew "git"
brew "neovim"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "stow"
brew "node"
# brew "zsh"
cask "alacritty"
